/*string firstVariable = 'I am the first';
system.debug(firstVariable);

string firstName = 'Esra';
string lastName = 'Arcan';
string fullName = firstName + ' ' + lastName;
system.debug('full name is ' + fullName);*/

//primitiveDataTypeDemo
    //when can we call the class or method?
//creating new instance of class 
    //object of the class.
PrimitiveDataTypeDemo prObj1 = new PrimitiveDataTypeDemo();
prObj1.printBasicDataType();
